
# RUN: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'
name: example
version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379" # Redis server port
      - "8001:8001" # RedisInsight (GUI) port
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432" # PostgreSQL server port
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  nats:
    container_name: nats-server
    image: nats:2.10.18
    command: '-js'
    ports:
      - '4222:4222'
    environment:
      NATS_ADDRESS: nats://nats:4222

  nats-ui:
    container_name: nats-ui
    image: ghcr.io/nats-nui/nui:0.4
    ports:
      - '31311:31311'
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging

  tempo:
    image: grafana/tempo:2.4.1
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "14250:14250"
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    depends_on:
      - loki
    logging: *default-logging

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/:/etc/grafana/provisioning/datasources
    depends_on:
      - loki
      - prometheus
    logging: *default-logging
